export default {
  products: [
    {
      _id: '1',
      name: 'Silver Angel wing',
      category: 'Necklaces',
      image: 'images/1.JPG',
      price: 15000,
      brand: 'LuxuryThingByZen',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '2',
      name: 'Gold Necklace',
      category: '2 sets',
      image: 'images/2.JPG',
      price: 30000,
      brand: 'LuxuryThingByZen',
      rating: 2.5,
      numReviews: 9,
      countInStock: 6,
    },
    {
      _id: '3',
      name: 'Gold rose Necklace',
      category: 'Necklaces',
      image: 'images/3.JPG',
      price: 15000,
      brand: 'LuxuryThingByZen',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '4',
      name: 'Silver Thin Necklace',
      category: 'Necklaces',
      image: 'images/4.JPG',
      price: 10000,
      brand: 'LuxuryThingByZen',
      rating: 3.5,
      numReviews: 8,
      countInStock: 6,
    },
    {
      _id: '5',
      name: 'Top Bronze Bracelet',
      category: 'Bracelets',
      image: 'images/5.JPG',
      price: 12000,
      brand: 'LuxuryThingByZen',
      rating: 4.5,
      numReviews: 19,
      countInStock: 6,
    },
    {
      _id: '6',
      name: 'Gold Necklace',
      category: 'Necklaces',
      image: 'images/6.JPG',
      price: 45000,
      brand: 'LuxuryThingByZen',
      rating: 4.5,
      numReviews: 10,
      countInStock: 0,
    },

  ],
};
